In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
from tensorflow.keras import layers

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense

In [2]:
# import tensorflow as tf
import numpy as np

input = np.array([
  [1, 2, 3, 4, 5],
  [1, 2, 3, 4, 5]
])
input_len = len(input[0])
batch_size = len(input)
print("input_len:", input_len)
print("batch_size:", batch_size)
x = tf.constant(input, dtype=tf.float32)


units=1
dense_layer = tf.keras.layers.Dense(units=units, activation='linear', use_bias=True, name='my_dense_layer')


# Manually set the weights and bias for the layer
# There will be one weight for each input, and one bias for the neuron
# Weights: w1=0.5, w2=1.5
# Bias: b=1.0

# weights must have shape (input_len, units)
weights = np.array([[0.5], [0.5], [0.5], [0.5], [0.5]])
#weights = np.array([[0.5, 0.5, 0.5], [0.5, 0.5, 0.5], [0.5,0.5, 0.5], [0.5,0.5, 0.5], [0.5,0.5, 0.5]])
print("weights.shape:", weights.shape)

# bias must have shape (, units)
# bias = np.array([1.0, 1.0, 1.0])
bias = np.array([1.0])
print("bias.shape:", bias.shape)

dense_layer.build(input_shape=(1, input_len)) # not sure what the 1 means ..
dense_layer.set_weights([weights, bias])

# Pass the input through the dense layer
y = dense_layer(x)

print("Inputs (x):", x.numpy())
print("Weights (w):\n", dense_layer.get_weights()[0]) # [0]) # [0].numpy().T)
print("Bias (b):\n", dense_layer.get_weights()[1])

# output will have shape (batch_size, units)
print("Output shape:\n", y.shape)
print("Output (y):\n", y.numpy())
print("Build config:", dense_layer.get_build_config())


input_len: 5
batch_size: 2
weights.shape: (5, 1)
bias.shape: (1,)
Inputs (x): [[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
Weights (w):
 [[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]]
Bias (b):
 [1.]
Output shape:
 (2, 1)
Output (y):
 [[8.5]
 [8.5]]
Build config: None


In [3]:
input @ weights + bias

array([[8.5],
       [8.5]])

In [23]:
input = np.array([
  [
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
  ],
  [
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
  ],
])
print("input.shape:", input.shape)
embed_dim = len(input[0][0])
input_len = len(input[0])
batch_size = len(input)
print("embed_dim:", embed_dim)
print("input_len:", input_len)
print("batch_size:", batch_size)
x = tf.constant(input, dtype=tf.float32)


units=3
dense_layer = tf.keras.layers.Dense(units=units, activation='linear', use_bias=False, name='my_dense_layer')

# weights must have shape (input_len, units)
# weights = np.array([[0.5, 0.5, 0.5], [0.5, 0.5, 0.5], [0.5,0.5, 0.5], [0.5,0.5, 0.5], [0.5,0.5, 0.5]])
weights = np.array([[0.5, 0.5, 0.5, 0.5, 0.5 ]])
# bias must have shape (, units)
# bias = np.array([1.0, 1.0, 1.0, 1.0, 1.0])
# bias = np.array([1.0])
# print("bias.shape:", bias.shape)

# dense_layer.build(input_shape=(1, input_len)) # not sure what the 1 means ..
# dense_layer.set_weights(weights)
y = dense_layer(x)

input.shape: (2, 3, 5)
embed_dim: 5
input_len: 3
batch_size: 2


In [24]:
dense_layer.get_weights()

[array([[-0.30218875,  0.8243012 , -0.6245928 ],
        [-0.15837228, -0.6514756 ,  0.39019316],
        [-0.73878527, -0.75800633, -0.09749162],
        [-0.69868773,  0.19652003, -0.4667101 ],
        [ 0.4655016 ,  0.6281473 ,  0.7307876 ]], dtype=float32)]

In [25]:
y

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-3.3025322,  1.1741476,  1.6504161],
        [-3.3025322,  1.1741476,  1.6504161],
        [-3.3025322,  1.1741476,  1.6504161]],

       [[-3.3025322,  1.1741476,  1.6504161],
        [-3.3025322,  1.1741476,  1.6504161],
        [-3.3025322,  1.1741476,  1.6504161]]], dtype=float32)>

In [31]:
# Note, weights is a list of arrays
print("weights shape:", len(dense_layer.get_weights()) ,dense_layer.get_weights()[0].shape )


weights shape: 1 (5, 3)


# Embedding
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding


In [32]:
input_dim = 10 # vocab_size
output_dim = 3 # the number of "features"

embedding_layer = tf.keras.layers.Embedding(input_dim=input_dim, output_dim=output_dim, name='my_embedding_layer')


In [35]:
input = tf.constant([[1,2,3,4,5], [1,2,3,4,5]])

embedding_layer(input)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[ 0.04082367, -0.01132127, -0.01002828],
        [-0.01644867,  0.03668428, -0.00024289],
        [-0.02417375, -0.04031194,  0.04733041],
        [-0.02158575, -0.03997653,  0.01214267],
        [-0.01593864,  0.01695111,  0.03237135]],

       [[ 0.04082367, -0.01132127, -0.01002828],
        [-0.01644867,  0.03668428, -0.00024289],
        [-0.02417375, -0.04031194,  0.04733041],
        [-0.02158575, -0.03997653,  0.01214267],
        [-0.01593864,  0.01695111,  0.03237135]]], dtype=float32)>

In [45]:
vv = [1,2,3]

In [47]:
help(vv.extend)

Help on built-in function extend:

extend(iterable, /) method of builtins.list instance
    Extend list by appending elements from the iterable.

