In [37]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
import numpy as np

In [34]:
# units=units, 
dense_layer = tf.keras.layers.Dense(units=3, use_bias=False, name='my_dense_layer', activation='softmax') # activation='linear', 

In [35]:
x = tf.constant([[10,10]])
dense_layer(x)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.0787294e-04, 5.3919578e-04, 9.9935287e-01]], dtype=float32)>

In [36]:
dense_layer.get_weights()

[array([[ 0.40219116,  0.5321864 ,  1.0373437 ],
        [-0.28700072, -0.25608343, -0.00876236]], dtype=float32)]

In [27]:
dense_layer.get_config()

{'name': 'my_dense_layer',
 'trainable': True,
 'dtype': 'float32',
 'units': 3,
 'activation': 'softmax',
 'use_bias': False,
 'kernel_initializer': {'module': 'keras.initializers',
  'class_name': 'GlorotUniform',
  'config': {'seed': None},
  'registered_name': None},
 'bias_initializer': {'module': 'keras.initializers',
  'class_name': 'Zeros',
  'config': {},
  'registered_name': None},
 'kernel_regularizer': None,
 'bias_regularizer': None,
 'activity_regularizer': None,
 'kernel_constraint': None,
 'bias_constraint': None}

In [38]:
w = np.array([[0.5, 0.5, 0.5], [0.1, 0.1, 0.1]])

In [39]:
dense_layer.set_weights([w])

In [40]:
dense_layer.get_weights()

[array([[0.5, 0.5, 0.5],
        [0.1, 0.1, 0.1]], dtype=float32)]

In [41]:
dense_layer(x)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.33333334, 0.33333334, 0.33333334]], dtype=float32)>

In [57]:
dense_linear = tf.keras.layers.Dense(units=3, use_bias=False, name='my_dense_layer', activation='linear') # activation='linear',
dense_linear.build((100, 2))

In [58]:
dense_linear.set_weights([w])

In [59]:
dense_linear(x)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[6., 6., 6.]], dtype=float32)>

In [61]:
y = tf.constant([[10,10], [10,10], [10,10]])
dense_layer(y)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.33333334, 0.33333334, 0.33333334],
       [0.33333334, 0.33333334, 0.33333334],
       [0.33333334, 0.33333334, 0.33333334]], dtype=float32)>

In [79]:
dense_relu = tf.keras.layers.Dense(units=3, use_bias=False, name='my_dense_layer', activation='relu', input_shape=(10,20))
# dense_relu.set_weights([w])
dense_relu.get_weights()

[]

In [77]:
dense_relu(x)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.        , 0.48308134, 2.4555478 ]], dtype=float32)>

In [78]:
dense_relu.get_weights()

[array([[-1.0504642 ,  0.27327025, -0.7603225 ],
        [-0.2884372 , -0.22496212,  1.0058773 ]], dtype=float32)]